# Generated by Django 5.0.14 on 2025-10-08 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupo', '0002_initial'),
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profesor.profesor'),
        ),
    ]
