# Generated by Django 5.0.14 on 2025-10-17 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0003_initial'),
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos', to='profesor.profesor'),
        ),
    ]
