# Generated by Django 5.0.14 on 2026-03-18 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0004_alter_grupo_profesor'),
        ('monitor_academico', '0001_initial'),
        ('oferta_academica', '0002_alter_ofertaacademica_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='oferta_academica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='oferta_academica.ofertaacademica'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='monitor_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor_academico.monitoracademico'),
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together={('nombre', 'oferta_academica')},
        ),
    ]
