# Generated by Django 5.0.14 on 2025-09-24 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoAcademico',
            fields=[
                ('id_seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observaciones', models.TextField()),
                ('id_inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.inscripcion')),
            ],
            options={
                'verbose_name': 'Seguimiento Academico',
                'verbose_name_plural': 'Seguimientos Academicos',
                'ordering': ['fecha'],
            },
        ),
    ]
