# Generated by Django 5.0.14 on 2026-03-12 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0004_inscripcion_audit_recibo_servicio_and_more'),
        ('seguimiento_academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seguimientoacademico',
            options={'verbose_name': 'Seguimiento Académico', 'verbose_name_plural': 'Seguimientos Académicos'},
        ),
        migrations.RemoveField(
            model_name='seguimientoacademico',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='seguimientoacademico',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='seguimientoacademico',
            name='fecha',
        ),
        migrations.AddField(
            model_name='seguimientoacademico',
            name='fecha_ultimo_cambio',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='seguimientoacademico',
            name='nota_conceptual_docente',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='seguimientoacademico',
            name='nota_conceptual_estudiante',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='seguimientoacademico',
            name='seguimiento_1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='seguimientoacademico',
            name='seguimiento_2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='seguimientoacademico',
            name='id_inscripcion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento', to='inscripcion.inscripcion'),
        ),
        migrations.AlterField(
            model_name='seguimientoacademico',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
