version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/api

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ec2-user

  AfterInstall:
    - location: scripts/install.sh
      timeout: 120
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ec2-user
