version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/api
    file_exists_behavior: OVERWRITE  # Sobrescribe archivos existentes

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: ubuntu
      ignoreFailure: true
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/permissions.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu
