services:
  backend:
    build:
      context: ./HTTP
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn semillero_backend.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080"
    volumes:
      - ./HTTP:/app
      - static_volume:/app/staticfiles
    container_name: semillero_backend
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - DEBUG=0
    networks:
      - semillero-net

  nginx:
    image: nginx:alpine
    container_name: semillero_nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMINIO=${DOMINIO}
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - static_volume:/app/staticfiles
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
    networks:
      - semillero-net

  certbot:
    image: certbot/certbot
    container_name: semillero_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - semillero-net

  redis:
    image: redis:7
    container_name: semillero_redis
    ports:
      - "6379:6379"
    networks:
      - semillero-net

networks:
  semillero-net:
    external: true

volumes:
  static_volume:
