# Generated by Django 5.1.7 on 2025-05-22 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('oferta_categoria', '0004_ofertacategoria_fecha_finalizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertacategoria',
            name='id_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oferta_categoria', to='categoria.categoria'),
        ),
    ]
