# Generated by Django 5.0.14 on 2025-09-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_categoria', '0005_alter_ofertacategoria_id_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertacategoria',
            name='precio_univalle_egresados',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
