# Generated by Django 5.0.14 on 2025-09-18 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_academica', '0002_alter_ofertaacademica_estado'),
        ('oferta_categoria', '0006_ofertacategoria_precio_univalle_egresados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertacategoria',
            name='id_oferta_academica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oferta_academica', to='oferta_academica.ofertaacademica'),
        ),
    ]
