# Generated by Django 5.1.7 on 2025-04-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_administrador_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
