# Generated by Django 5.1.7 on 2025-04-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_alter_administrador_fecha_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='correo',
            field=models.EmailField(max_length=100),
        ),
    ]
