# Generated by Django 5.1.7 on 2025-04-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0002_profesor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='correo',
            field=models.EmailField(max_length=100),
        ),
    ]
