# Generated by Django 5.1.7 on 2025-06-05 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0006_rename_ditigido_a_modulo_dirigido_a'),
        ('profesor', '0002_rename_telefono_profesor_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='area_desempeño',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='grado_escolaridad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesores', to='modulo.modulo'),
        ),
    ]
