# Generated by Django 5.0.14 on 2025-10-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='imagen_area',
            field=models.ImageField(blank=True, null=True, upload_to='areas/'),
        ),
    ]
