# Generated by Django 5.0.14 on 2025-09-24 19:10

import django.db.models.deletion
import profesor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.usuario')),
                ('area_desempeño', models.CharField(max_length=50)),
                ('grado_escolaridad', models.CharField(max_length=50)),
                ('hoja_vida_pdf', models.FileField(blank=True, null=True, upload_to=profesor.models.hoja_vida_upload_to)),
                ('certificado_laboral_pdf', models.FileField(blank=True, null=True, upload_to=profesor.models.certificado_laboral_upload_to)),
                ('certificado_academico_pdf', models.FileField(blank=True, null=True, upload_to=profesor.models.certificado_academico_upload_to)),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesores', to='modulo.modulo')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ['id'],
            },
            bases=('usuario.usuario',),
        ),
    ]
