# Generated by Django 5.1.7 on 2025-05-05 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_profesor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ['id_profesor'],
            },
        ),
    ]
