# Generated by Django 5.0.14 on 2025-10-08 23:29

import django.db.models.deletion
import profesor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditlog', '0017_add_actor_email'),
        ('modulo', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.usuario')),
                ('area_desempeño', models.CharField(max_length=50)),
                ('grado_escolaridad', models.CharField(max_length=50)),
                ('hoja_vida_pdf', models.FileField(blank=True, null=True, upload_to=profesor.models.hoja_vida_upload_to)),
                ('certificado_laboral_pdf', models.FileField(blank=True, null=True, upload_to=profesor.models.certificado_laboral_upload_to)),
                ('certificado_academico_pdf', models.FileField(blank=True, null=True, upload_to=profesor.models.certificado_academico_upload_to)),
                ('verificacion_hoja_vida', models.BooleanField(default=False)),
                ('verificacion_certificado_laboral', models.BooleanField(default=False)),
                ('verificacion_certificado_academico', models.BooleanField(default=False)),
                ('verificacion_documento_identidad', models.BooleanField(default=False)),
                ('verificacion_rut', models.BooleanField(default=False)),
                ('verificacion_certificado_bancario', models.BooleanField(default=False)),
                ('verificacion_foto', models.BooleanField(default=False)),
                ('verificacion_informacion', models.BooleanField(default=False)),
                ('audit_certificado_academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesor_estado_mat_financiera', to='auditlog.logentry')),
                ('audit_certificado_bancario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesor_certificado_bancario', to='auditlog.logentry')),
                ('audit_certificado_laboral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesor_tabulado', to='auditlog.logentry')),
                ('audit_documento_identidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesor_documento_identidad', to='auditlog.logentry')),
                ('audit_foto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesor_foto', to='auditlog.logentry')),
                ('audit_hoja_vida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesor_d10', to='auditlog.logentry')),
                ('audit_informacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesor_informacion', to='auditlog.logentry')),
                ('audit_rut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesor_rut', to='auditlog.logentry')),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesores', to='modulo.modulo')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ['id'],
            },
            bases=('usuario.usuario',),
        ),
    ]
