# Generated by Django 5.1.7 on 2025-06-05 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='telefono',
            new_name='celular',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='correo',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='fecha_contratacion',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='salario',
        ),
    ]
