# Generated by Django 5.0.14 on 2025-09-29 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0017_add_actor_email'),
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='audit_certificado_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesor_estado_mat_financiera', to='auditlog.logentry'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='audit_certificado_bancario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesor_certificado_bancario', to='auditlog.logentry'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='audit_certificado_laboral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesor_tabulado', to='auditlog.logentry'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='audit_documento_identidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesor_documento_identidad', to='auditlog.logentry'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='audit_hoja_vida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesor_d10', to='auditlog.logentry'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='audit_rut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesor_rut', to='auditlog.logentry'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='verificacion_certificado_academico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profesor',
            name='verificacion_certificado_bancario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profesor',
            name='verificacion_certificado_laboral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profesor',
            name='verificacion_documento_identidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profesor',
            name='verificacion_hoja_vida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profesor',
            name='verificacion_rut',
            field=models.BooleanField(default=False),
        ),
    ]
