# Generated by Django 5.0.14 on 2025-09-20 17:45

import profesor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0003_profesor_area_desempeño_profesor_grado_escolaridad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='documento_identidad_pdf',
            field=models.FileField(blank=True, help_text='Sube un documento pdf del documento de identidad del profesor', null=True, upload_to=profesor.models.documento_identidad_upload_to),
        ),
    ]
