# Generated by Django 5.1.7 on 2025-05-01 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('categoria', '0001_initial'),
        ('modulo', '0002_modulo_id_oferta_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='descripcion_modulo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='id_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modulo', to='categoria.categoria'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='id_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modulo', to='area.area'),
        ),
    ]
