# Generated by Django 5.1.7 on 2025-05-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0003_modulo_descripcion_modulo_modulo_id_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='nombre_modulo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
