# Generated by Django 5.1.7 on 2025-05-01 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0004_alter_modulo_nombre_modulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['id_modulo'], 'verbose_name': 'Modulo', 'verbose_name_plural': 'Modulos'},
        ),
        migrations.AlterModelTable(
            name='modulo',
            table='modulo',
        ),
    ]
