# Generated by Django 5.1.7 on 2025-04-15 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acudiente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('registro_fase', models.PositiveSmallIntegerField(default=1)),
                ('ciudad_residencia', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('id_eps', models.CharField(blank=True, max_length=20, null=True)),
                ('id_grado', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('genero', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono_fijo', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('departamento_residencia', models.CharField(blank=True, max_length=100, null=True)),
                ('comuna_residencia', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_residencia', models.CharField(blank=True, max_length=255, null=True)),
                ('estamento', models.CharField(blank=True, max_length=50, null=True)),
                ('discapacidad', models.BooleanField(default=False)),
                ('tipo_discapacidad', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_discapacidad', models.TextField(blank=True, null=True)),
                ('acudiente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='acudiente.acudiente')),
            ],
        ),
    ]
