# Generated by Django 5.1.7 on 2025-05-08 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acudiente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('contrasena', models.CharField(blank=True, max_length=128)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('ciudad_residencia', models.CharField(max_length=100)),
                ('ciudad_documento', models.CharField(max_length=100)),
                ('eps', models.CharField(max_length=100)),
                ('grado', models.CharField(max_length=20)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono_fijo', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=15)),
                ('departamento_residencia', models.CharField(max_length=50)),
                ('comuna_residencia', models.CharField(max_length=10)),
                ('direccion_residencia', models.CharField(max_length=255)),
                ('estamento', models.CharField(max_length=50)),
                ('discapacidad', models.BooleanField(default=False)),
                ('tipo_discapacidad', models.CharField(default='Ninguna', max_length=50)),
                ('descripcion_discapacidad', models.TextField(default='Ninguna', max_length=100)),
                ('acudiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='acudiente.acudiente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['id_estudiante'],
            },
        ),
    ]
