# Generated by Django 5.1.7 on 2025-04-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='contrasena',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
