# Generated by Django 5.1.7 on 2025-05-07 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acudiente', '0002_rename_numero_documento_acudiente_numero_documento_acudiente_and_more'),
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='acudiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='acudiente.acudiente'),
        ),
    ]
