# Generated by Django 5.1.7 on 2025-05-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='documento_identidad',
            field=models.FileField(blank=True, help_text='Sube una imagen del documento de identidad del estudiante', null=True, upload_to='estudiantes/documentos_identidad/'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='foto',
            field=models.ImageField(blank=True, help_text='Sube una imagen del estudiante', null=True, upload_to='estudiantes/fotos/'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='recibo_pago',
            field=models.FileField(blank=True, help_text='Sube una imagen del recibo de pago del estudiante', null=True, upload_to='estudiantes/recibos_pago/'),
        ),
    ]
