# Generated by Django 5.1.7 on 2025-05-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_alter_estudiante_acudiente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='id_eps',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='eps',
            field=models.CharField(default='eps', max_length=100),
            preserve_default=False,
        ),
    ]
