# Generated by Django 5.1.7 on 2025-04-23 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acudiente', '0001_initial'),
        ('estudiante', '0003_estudiante_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='acudiente',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='acudiente.acudiente'),
        ),
    ]
