# Generated by Django 5.1.7 on 2025-05-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0003_estudiante_constancia_estudios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='constancia_estudios',
            field=models.FileField(blank=True, help_text='Sube una imagen de la constancia de estudios del estudiante', null=True, upload_to='constancias/'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='documento_identidad',
            field=models.FileField(blank=True, help_text='Sube una imagen del documento de identidad del estudiante', null=True, upload_to='documentos_identidad/'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='foto',
            field=models.ImageField(blank=True, help_text='Sube una imagen del estudiante', null=True, upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='recibo_pago',
            field=models.FileField(blank=True, help_text='Sube una imagen del recibo de pago del estudiante', null=True, upload_to='recibos_pago/'),
        ),
    ]
