# Generated by Django 5.0.14 on 2025-06-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0006_remove_estudiante_ciudad_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='area_desempeño',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='colegio',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='grado_escolaridad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
