# Generated by Django 5.0.14 on 2025-10-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id_acudiente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_acudiente', models.CharField(max_length=100)),
                ('apellido_acudiente', models.CharField(max_length=100)),
                ('tipo_documento_acudiente', models.CharField(max_length=20)),
                ('numero_documento_acudiente', models.CharField(max_length=20)),
                ('celular_acudiente', models.CharField(max_length=20)),
                ('email_acudiente', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Acudiente',
                'verbose_name_plural': 'Acudientes',
                'ordering': ['id_acudiente'],
            },
        ),
    ]
