# Generated by Django 5.0.14 on 2026-01-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acudiente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acudiente',
            name='numero_documento_acudiente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='acudiente',
            name='tipo_documento_acudiente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
