# Generated by Django 5.1.7 on 2025-05-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acudiente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acudiente',
            name='email_acudiente',
            field=models.EmailField(default='primeros@gmail.com', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
