# Generated by Django 5.0.14 on 2025-06-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acudiente', '0002_acudiente_email_acudiente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acudiente',
            name='email_acudiente',
        ),
        migrations.AlterField(
            model_name='acudiente',
            name='tipo_documento_acudiente',
            field=models.CharField(max_length=20),
        ),
    ]
