# Generated by Django 5.0.14 on 2025-09-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acudiente', '0003_remove_acudiente_email_acudiente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acudiente',
            name='email_acudiente',
            field=models.CharField(default='noemail@example.com', max_length=50),
            preserve_default=False,
        ),
    ]
