# Generated by Django 5.1.7 on 2025-04-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EPS',
            fields=[
                ('id_eps', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_eps', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
