# Generated by Django 5.1.7 on 2025-05-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EPS',
            fields=[
                ('id_eps', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_eps', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'EPS',
                'verbose_name_plural': 'EPS',
                'ordering': ['nombre_eps'],
            },
        ),
    ]
