# Generated by Django 5.1.7 on 2025-05-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionPrograma',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('nota_metodologia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota_estudiante', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota_profesor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota_monitor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observaciones', models.TextField(default='Ninguna', max_length=500)),
            ],
            options={
                'verbose_name': 'Evaluacion Programa',
                'verbose_name_plural': 'Evaluaciones Programas',
                'ordering': ['fecha'],
            },
        ),
    ]
