# Generated by Django 5.1.7 on 2025-04-15 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionPrograma',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('nota_metodologia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota_estudiante', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota_profesor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota_monitor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observaciones', models.TextField()),
                ('id_inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.inscripcion')),
            ],
            options={
                'verbose_name': 'Evaluacion Programa',
                'verbose_name_plural': 'Evaluaciones Programas',
                'db_table': 'evaluacion_programa',
            },
        ),
    ]
