# Generated by Django 5.1.7 on 2025-05-08 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluacion_programa', '0001_initial'),
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionprograma',
            name='id_inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.inscripcion'),
        ),
    ]
