# Generated by Django 5.0.14 on 2025-09-24 19:10

import django.db.models.deletion
import inscripcion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0001_initial'),
        ('modulo', '0001_initial'),
        ('oferta_categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
                ('grupo', models.CharField(default='Grupo 0', max_length=255)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('tipo_vinculacion', models.CharField(max_length=255)),
                ('terminos', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('recibo_pago', models.FileField(blank=True, help_text='Sube un documento pdf del recibo de pago', null=True, upload_to=inscripcion.models.recibo_pago_upload_to)),
                ('constancia', models.FileField(blank=True, help_text='Sube un documento pdf de la constancia de estudio', null=True, upload_to=inscripcion.models.constancia_upload_to)),
                ('certificado', models.FileField(blank=True, help_text='Sube un documento pdf del certificado de funcionario', null=True, upload_to=inscripcion.models.certificado_upload_to)),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
                ('id_modulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo.modulo')),
                ('id_oferta_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oferta_categoria.ofertacategoria')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['fecha_inscripcion'],
            },
        ),
    ]
