# Generated by Django 5.0.14 on 2025-10-08 23:29

import django.db.models.deletion
import inscripcion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditlog', '0017_add_actor_email'),
        ('estudiante', '0001_initial'),
        ('grupo', '0001_initial'),
        ('modulo', '0001_initial'),
        ('oferta_categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('tipo_vinculacion', models.CharField(max_length=255)),
                ('terminos', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('recibo_pago', models.FileField(blank=True, help_text='Sube un documento pdf del recibo de pago', null=True, upload_to=inscripcion.models.recibo_pago_upload_to)),
                ('constancia', models.FileField(blank=True, help_text='Sube un documento pdf de la constancia de estudio', null=True, upload_to=inscripcion.models.constancia_upload_to)),
                ('certificado', models.FileField(blank=True, help_text='Sube un documento pdf del certificado de funcionario', null=True, upload_to=inscripcion.models.certificado_upload_to)),
                ('verificacion_recibo_pago', models.BooleanField(default=False)),
                ('verificacion_constancia', models.BooleanField(default=False)),
                ('verificacion_certificado', models.BooleanField(default=False)),
                ('estado', models.CharField(default='No revisado', max_length=12)),
                ('audit_certificado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion_certificado', to='auditlog.logentry')),
                ('audit_constancia', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion_constancia', to='auditlog.logentry')),
                ('audit_documento_recibo_pago', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion_recibo_pago', to='auditlog.logentry')),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grupo.grupo')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
                ('id_modulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo.modulo')),
                ('id_oferta_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oferta_categoria.ofertacategoria')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['fecha_inscripcion'],
            },
        ),
    ]
