# Generated by Django 5.0.14 on 2025-10-15 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0001_initial'),
        ('oferta_academica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='oferta_academica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oferta_academica.ofertaacademica'),
        ),
    ]
