# Generated by Django 5.1.7 on 2025-05-23 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0001_initial'),
        ('modulo', '0004_alter_modulo_id_oferta_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='id_grupo',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='id_oferta_academica',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='grupo',
            field=models.CharField(default='Grupo 0', max_length=255),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='id_modulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo.modulo'),
        ),
    ]
