# Generated by Django 5.0.14 on 2025-09-28 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0017_add_actor_email'),
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='audit_certificado',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion_certificado', to='auditlog.logentry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='audit_constancia',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion_constancia', to='auditlog.logentry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='audit_documento_recibo_pago',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion_recibo_pago', to='auditlog.logentry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='verificacion_certificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='verificacion_constancia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='verificacion_recibo_pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(default='No revisado', max_length=12),
        ),
    ]
