# Generated by Django 5.0.14 on 2025-10-17 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0004_alter_grupo_profesor'),
        ('inscripcion', '0002_inscripcion_oferta_academica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matricula', to='grupo.grupo'),
        ),
    ]
