# Generated by Django 5.0.14 on 2025-09-28 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0017_add_actor_email'),
        ('inscripcion', '0002_inscripcion_audit_certificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='audit_certificado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion_certificado', to='auditlog.logentry'),
        ),
    ]
