# Generated by Django 5.0.14 on 2025-09-15 03:31

import inscripcion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0002_remove_inscripcion_id_grupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='certificado',
            field=models.FileField(blank=True, help_text='Sube un documento pdf del certificado de funcionario', null=True, upload_to=inscripcion.models.certificado_upload_to),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='constancia',
            field=models.FileField(blank=True, help_text='Sube un documento pdf de la constancia de estudio', null=True, upload_to=inscripcion.models.constancia_upload_to),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='recibo_pago',
            field=models.FileField(blank=True, help_text='Sube un documento pdf del recibo de pago', null=True, upload_to=inscripcion.models.recibo_pago_upload_to),
        ),
    ]
