# Generated by Django 5.0.14 on 2025-09-28 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0017_add_actor_email'),
        ('inscripcion', '0003_alter_inscripcion_audit_certificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='audit_constancia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion_constancia', to='auditlog.logentry'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='audit_documento_recibo_pago',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion_recibo_pago', to='auditlog.logentry'),
        ),
    ]
