# Generated by Django 5.0.14 on 2026-02-18 03:04

import django.db.models.deletion
import inscripcion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0017_add_actor_email'),
        ('inscripcion', '0003_alter_inscripcion_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='audit_recibo_servicio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion_recibo_servicio', to='auditlog.logentry'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='recibo_servicio',
            field=models.FileField(blank=True, help_text='Sube un documento pdf del recibo de servicio', null=True, upload_to=inscripcion.models.recibo_servicio),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='verificacion_recibo_servicio',
            field=models.BooleanField(default=False),
        ),
    ]
