# Generated by Django 5.0.14 on 2025-09-18 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0003_inscripcion_certificado_inscripcion_constancia_and_more'),
        ('oferta_categoria', '0006_ofertacategoria_precio_univalle_egresados'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='id_oferta_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oferta_categoria.ofertacategoria'),
        ),
    ]
