# Generated by Django 5.0.14 on 2026-07-11 03:15

import inscripcion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0004_inscripcion_audit_recibo_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='certificado_academico',
            field=models.FileField(blank=True, help_text='Sube un documento pdf del certificado académico', null=True, upload_to=inscripcion.models.certificado_academico_upload_to),
        ),
    ]
