# Generated by Django 5.0.14 on 2025-09-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0004_inscripcion_id_oferta_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
