# Generated by Django 5.0.14 on 2025-09-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCambios',
            fields=[
                ('id_cambio', models.AutoField(primary_key=True, serialize=False)),
                ('id_inscripcion', models.IntegerField()),
                ('tipo_cambio', models.CharField(max_length=50)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo_cambio', models.TextField(max_length=500)),
                ('id_nueva_inscripcion', models.IntegerField()),
                ('id_modulo_nuevo', models.IntegerField()),
                ('id_periodo_aplazado', models.IntegerField()),
                ('Observaciones', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Historial de Cambios',
                'verbose_name_plural': 'Historial de Cambios',
                'ordering': ['fecha_cambio'],
            },
        ),
    ]
