# Generated by Django 5.1.7 on 2025-05-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asistencia', models.DateField()),
                ('estado_asistencia', models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('T', 'Tarde')], default='P', max_length=20)),
                ('comentarios', models.TextField(default='Ninguno', max_length=500)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['fecha_asistencia'],
            },
        ),
    ]
