# Generated by Django 5.1.7 on 2025-04-15 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asistencia', models.DateField()),
                ('estado_asistencia', models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('T', 'Tarde')], default='P', max_length=20)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('id_inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.inscripcion')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'asistencia',
            },
        ),
    ]
