# Generated by Django 5.0.14 on 2025-09-24 19:10

import django.db.models.deletion
import monitor_academico.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorAcademico',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.usuario')),
                ('semestre', models.CharField(blank=True, max_length=100, null=True)),
                ('grado_escolaridad', models.CharField(max_length=50)),
                ('d10_pdf', models.FileField(blank=True, null=True, upload_to=monitor_academico.models.d10_upload_to)),
                ('tabulado_pdf', models.FileField(blank=True, null=True, upload_to=monitor_academico.models.tabulado_upload_to)),
                ('estado_mat_financiera_pdf', models.FileField(blank=True, null=True, upload_to=monitor_academico.models.estado_mat_financiera_upload_to)),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_academico', to='modulo.modulo')),
            ],
            options={
                'verbose_name': 'MonitorAcademico',
                'verbose_name_plural': 'MonitoresAcademicos',
                'ordering': ['id'],
            },
            bases=('usuario.usuario',),
        ),
    ]
