# Generated by Django 5.0.14 on 2025-10-08 23:29

import django.db.models.deletion
import monitor_academico.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditlog', '0017_add_actor_email'),
        ('modulo', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorAcademico',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.usuario')),
                ('semestre', models.CharField(blank=True, max_length=100, null=True)),
                ('area_desempeño', models.CharField(max_length=50)),
                ('d10_pdf', models.FileField(blank=True, null=True, upload_to=monitor_academico.models.d10_upload_to)),
                ('tabulado_pdf', models.FileField(blank=True, null=True, upload_to=monitor_academico.models.tabulado_upload_to)),
                ('estado_mat_financiera_pdf', models.FileField(blank=True, null=True, upload_to=monitor_academico.models.estado_mat_financiera_upload_to)),
                ('verificacion_d10', models.BooleanField(default=False)),
                ('verificacion_tabulado', models.BooleanField(default=False)),
                ('verificacion_estado_mat_financiera', models.BooleanField(default=False)),
                ('verificacion_documento_identidad', models.BooleanField(default=False)),
                ('verificacion_rut', models.BooleanField(default=False)),
                ('verificacion_certificado_bancario', models.BooleanField(default=False)),
                ('verificacion_foto', models.BooleanField(default=False)),
                ('verificacion_informacion', models.BooleanField(default=False)),
                ('audit_certificado_bancario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_academico_certificado_bancario', to='auditlog.logentry')),
                ('audit_d10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_academico_d10', to='auditlog.logentry')),
                ('audit_documento_identidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_academico_documento_identidad', to='auditlog.logentry')),
                ('audit_estado_mat_financiera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_academico_estado_mat_financiera', to='auditlog.logentry')),
                ('audit_foto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_academico_foto', to='auditlog.logentry')),
                ('audit_informacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_academico_informacion', to='auditlog.logentry')),
                ('audit_rut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_academico_rut', to='auditlog.logentry')),
                ('audit_tabulado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_academico_tabulado', to='auditlog.logentry')),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_academico', to='modulo.modulo')),
            ],
            options={
                'verbose_name': 'MonitorAcademico',
                'verbose_name_plural': 'MonitoresAcademicos',
                'ordering': ['id'],
            },
            bases=('usuario.usuario',),
        ),
    ]
