# Generated by Django 5.0.14 on 2025-09-24 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_academico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoracademico',
            old_name='grado_escolaridad',
            new_name='area_desempeño',
        ),
    ]
