# Generated by Django 5.0.14 on 2025-09-28 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0017_add_actor_email'),
        ('monitor_academico', '0002_rename_grado_escolaridad_monitoracademico_area_desempeño'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoracademico',
            name='audit_certificado_bancario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_academico_certificado_bancario', to='auditlog.logentry'),
        ),
        migrations.AddField(
            model_name='monitoracademico',
            name='audit_d10',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_academico_d10', to='auditlog.logentry'),
        ),
        migrations.AddField(
            model_name='monitoracademico',
            name='audit_documento_identidad',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_academico_documento_identidad', to='auditlog.logentry'),
        ),
        migrations.AddField(
            model_name='monitoracademico',
            name='audit_estado_mat_financiera',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_academico_estado_mat_financiera', to='auditlog.logentry'),
        ),
        migrations.AddField(
            model_name='monitoracademico',
            name='audit_rut',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_academico_rut', to='auditlog.logentry'),
        ),
        migrations.AddField(
            model_name='monitoracademico',
            name='audit_tabulado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_academico_tabulado', to='auditlog.logentry'),
        ),
        migrations.AddField(
            model_name='monitoracademico',
            name='verificacion_certificado_bancario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoracademico',
            name='verificacion_d10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoracademico',
            name='verificacion_documento_identidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoracademico',
            name='verificacion_estado_mat_financiera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoracademico',
            name='verificacion_rut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoracademico',
            name='verificacion_tabulado',
            field=models.BooleanField(default=False),
        ),
    ]
