# Generated by Django 5.0.14 on 2025-09-29 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0017_add_actor_email'),
        ('monitor_academico', '0003_monitoracademico_audit_certificado_bancario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoracademico',
            name='audit_certificado_bancario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_academico_certificado_bancario', to='auditlog.logentry'),
        ),
        migrations.AlterField(
            model_name='monitoracademico',
            name='audit_d10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_academico_d10', to='auditlog.logentry'),
        ),
        migrations.AlterField(
            model_name='monitoracademico',
            name='audit_documento_identidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_academico_documento_identidad', to='auditlog.logentry'),
        ),
        migrations.AlterField(
            model_name='monitoracademico',
            name='audit_estado_mat_financiera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_academico_estado_mat_financiera', to='auditlog.logentry'),
        ),
        migrations.AlterField(
            model_name='monitoracademico',
            name='audit_rut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_academico_rut', to='auditlog.logentry'),
        ),
        migrations.AlterField(
            model_name='monitoracademico',
            name='audit_tabulado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_academico_tabulado', to='auditlog.logentry'),
        ),
    ]
