# Generated by Django 5.0.14 on 2025-10-03 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0017_add_actor_email'),
        ('monitor_academico', '0004_alter_monitoracademico_audit_certificado_bancario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoracademico',
            name='audit_foto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_academico_foto', to='auditlog.logentry'),
        ),
        migrations.AddField(
            model_name='monitoracademico',
            name='audit_informacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_academico_informacion', to='auditlog.logentry'),
        ),
        migrations.AddField(
            model_name='monitoracademico',
            name='verificacion_foto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoracademico',
            name='verificacion_informacion',
            field=models.BooleanField(default=False),
        ),
    ]
