# Generated by Django 4.2.20 on 2025-03-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='CorreoElectronico',
            field=models.EmailField(default='default@default.com', max_length=254),
        ),
    ]
