# Generated by Django 5.1.7 on 2025-04-15 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0001_initial'),
        ('grupo', '0001_initial'),
        ('oferta_modulo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('convenio', models.CharField(max_length=255)),
                ('terminos', models.BooleanField(default=False)),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo.grupo')),
                ('id_oferta_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferta_modulo.ofertamodulo')),
            ],
        ),
    ]
