# Generated by Django 5.0.14 on 2025-11-26 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PruebaDiagnostica',
            fields=[
                ('id_prueba', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('id_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_diagnosticas', to='modulo.modulo', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Prueba Diagnóstica',
                'verbose_name_plural': 'Pruebas Diagnósticas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaDiagnostica',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('texto_pregunta', models.TextField(verbose_name='Pregunta')),
                ('tipo_pregunta', models.CharField(choices=[('multiple', 'Opción Múltiple'), ('verdadero_falso', 'Verdadero/Falso')], default='multiple', max_length=20, verbose_name='Tipo de Pregunta')),
                ('puntaje', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Puntaje')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='preguntas_diagnosticas/', verbose_name='Imagen')),
                ('explicacion', models.TextField(blank=True, help_text='Explicación de la respuesta correcta', null=True, verbose_name='Explicación')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('id_prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='prueba_diagnostica.pruebadiagnostica', verbose_name='Prueba Diagnóstica')),
            ],
            options={
                'verbose_name': 'Pregunta Diagnóstica',
                'verbose_name_plural': 'Preguntas Diagnósticas',
                'ordering': ['id_prueba', 'fecha_creacion'],
                'unique_together': {('id_prueba', 'fecha_creacion')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaDiagnostica',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('texto_respuesta', models.TextField(verbose_name='Respuesta')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='¿Es Correcta?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='prueba_diagnostica.preguntadiagnostica', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta Diagnóstica',
                'verbose_name_plural': 'Respuestas Diagnósticas',
                'ordering': ['id_pregunta', 'fecha_creacion'],
                'unique_together': {('id_pregunta', 'fecha_creacion')},
            },
        ),
    ]
