# Generated by Django 5.0.14 on 2025-11-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_diagnostica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruebadiagnostica',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='pruebadiagnostica',
            name='nombre_prueba',
            field=models.CharField(default='otro', max_length=200, verbose_name='Nombre de la Prueba'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruebadiagnostica',
            name='puntaje_minimo',
            field=models.DecimalField(decimal_places=2, default=60.0, help_text='Puntaje mínimo para aprobar (%)', max_digits=5, verbose_name='Puntaje Mínimo (%)'),
        ),
        migrations.AddField(
            model_name='pruebadiagnostica',
            name='tiempo_limite',
            field=models.PositiveIntegerField(default=60, help_text='Tiempo límite en minutos', verbose_name='Tiempo Límite (min)'),
        ),
    ]
