# Generated by Django 5.0.14 on 2025-12-12 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_diagnostica', '0002_pruebadiagnostica_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preguntadiagnostica',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='preguntadiagnostica',
            name='id_prueba',
            field=models.ForeignKey(blank=True, help_text='Dejar vacío para crear una pregunta en el banco de preguntas', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='prueba_diagnostica.pruebadiagnostica', verbose_name='Prueba Diagnóstica'),
        ),
    ]
