# Generated by Django 5.0.14 on 2026-03-12 08:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscripcion', '0004_inscripcion_audit_recibo_servicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaSatisfaccion',
            fields=[
                ('id_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('nota_modulo', models.DecimalField(blank=True, decimal_places=1, help_text='Calificación del estudiante al contenido del módulo (0.0 – 5.0)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Nota al módulo')),
                ('nota_docente', models.DecimalField(blank=True, decimal_places=1, help_text='Calificación del estudiante al desempeño del docente (0.0 – 5.0)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Nota al docente')),
                ('nota_monitor', models.DecimalField(blank=True, decimal_places=1, help_text='Calificación del estudiante al desempeño del monitor (0.0 – 5.0)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Nota al monitor')),
                ('nota_estudiante', models.DecimalField(blank=True, decimal_places=1, help_text='Autoevaluación del estudiante (0.0 – 5.0)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Autoevaluación del estudiante')),
                ('comentarios', models.TextField(blank=True, help_text='Observaciones o sugerencias del estudiante', null=True, verbose_name='Comentarios')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de respuesta')),
                ('fecha_ultimo_cambio', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('id_inscripcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encuesta_satisfaccion', to='inscripcion.inscripcion', verbose_name='Inscripción')),
            ],
            options={
                'verbose_name': 'Encuesta de Satisfacción',
                'verbose_name_plural': 'Encuestas de Satisfacción',
                'ordering': ['-fecha_respuesta'],
            },
        ),
    ]
