# Generated by Django 5.1.7 on 2025-03-31 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Foto',
            field=models.FileField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='comprobante_pago',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes_pago/'),
        ),
        migrations.AddField(
            model_name='student',
            name='comuna',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='constancia_estudios',
            field=models.FileField(blank=True, null=True, upload_to='constancias_estudios/'),
        ),
        migrations.AddField(
            model_name='student',
            name='departamento_residencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='descripcion_discapacidad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='discapacidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='documento_identidad',
            field=models.FileField(blank=True, null=True, upload_to='documentos_identidad/'),
        ),
        migrations.AddField(
            model_name='student',
            name='estamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='genero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_phase',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='tipo_discapacidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
