# Generated by Django 5.1.7 on 2025-04-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_foto_student_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tipo_identificacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
