# Generated by Django 5.0.14 on 2025-09-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaAcademica',
            fields=[
                ('id_oferta_academica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Oferta Académica',
                'verbose_name_plural': 'Ofertas Académicas',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
