# Generated by Django 5.0.14 on 2025-09-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_academica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaacademica',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
