# Generated by Django 5.0.14 on 2026-03-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_academica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ofertaacademica',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Oferta Académica', 'verbose_name_plural': 'Ofertas Académicas'},
        ),
        migrations.AddField(
            model_name='ofertaacademica',
            name='fecha_desarrollo',
            field=models.DateField(blank=True, help_text='Fecha de inicio de las clases/desarrollo', null=True),
        ),
        migrations.AlterField(
            model_name='ofertaacademica',
            name='estado',
            field=models.CharField(choices=[('inscripcion', 'En Inscripciones'), ('desarrollo', 'En Desarrollo'), ('finalizado', 'Finalizado')], default='inscripcion', max_length=20),
        ),
        migrations.AlterField(
            model_name='ofertaacademica',
            name='fecha_inicio',
            field=models.DateField(help_text='Fecha de inicio de las inscripciones'),
        ),
    ]
