# Generated by Django 5.0.14 on 2025-09-24 19:10

import django.db.models.deletion
import monitor_administrativo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorAdministrativo',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.usuario')),
                ('d10_pdf', models.FileField(blank=True, null=True, upload_to=monitor_administrativo.models.d10_upload_to)),
                ('tabulado_pdf', models.FileField(blank=True, null=True, upload_to=monitor_administrativo.models.tabulado_upload_to)),
                ('estado_mat_financiera_pdf', models.FileField(blank=True, null=True, upload_to=monitor_administrativo.models.estado_mat_financiera_upload_to)),
            ],
            options={
                'verbose_name': 'MonitorAdministrativo',
                'verbose_name_plural': 'MonitoresAdministrativos',
                'ordering': ['id'],
            },
            bases=('usuario.usuario',),
        ),
    ]
