# Generated by Django 5.0.14 on 2025-09-29 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0017_add_actor_email'),
        ('monitor_administrativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoradministrativo',
            name='audit_certificado_bancario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_administrativo_certificado_bancario', to='auditlog.logentry'),
        ),
        migrations.AddField(
            model_name='monitoradministrativo',
            name='audit_d10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_administrativo_d10', to='auditlog.logentry'),
        ),
        migrations.AddField(
            model_name='monitoradministrativo',
            name='audit_documento_identidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_administrativo_documento_identidad', to='auditlog.logentry'),
        ),
        migrations.AddField(
            model_name='monitoradministrativo',
            name='audit_estado_mat_financiera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_administrativo_estado_mat_financiera', to='auditlog.logentry'),
        ),
        migrations.AddField(
            model_name='monitoradministrativo',
            name='audit_rut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_administrativo_rut', to='auditlog.logentry'),
        ),
        migrations.AddField(
            model_name='monitoradministrativo',
            name='audit_tabulado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_administrativo_tabulado', to='auditlog.logentry'),
        ),
        migrations.AddField(
            model_name='monitoradministrativo',
            name='verificacion_certificado_bancario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoradministrativo',
            name='verificacion_d10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoradministrativo',
            name='verificacion_documento_identidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoradministrativo',
            name='verificacion_estado_mat_financiera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoradministrativo',
            name='verificacion_rut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoradministrativo',
            name='verificacion_tabulado',
            field=models.BooleanField(default=False),
        ),
    ]
