# Generated by Django 5.1.7 on 2025-04-21 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        ('oferta_academica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaCategoria',
            fields=[
                ('id_oferta_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('precio_publico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_privado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_finalizacion', models.DateField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='categoria.categoria', verbose_name='Categoría')),
                ('id_oferta_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oferta_categoria', to='oferta_academica.ofertaacademica')),
            ],
        ),
    ]
