# Generated by Django 5.1.7 on 2025-04-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_categoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertacategoria',
            name='precio_univalle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
