# Generated by Django 5.1.7 on 2025-05-22 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('oferta_academica', '0001_initial'),
        ('oferta_categoria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertacategoria',
            name='fecha_finalizacion',
        ),
        migrations.AddField(
            model_name='ofertacategoria',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ofertacategoria',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oferta_categoria', to='categoria.categoria'),
        ),
        migrations.AlterField(
            model_name='ofertacategoria',
            name='id_oferta_academica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oferta_categoria', to='oferta_academica.ofertaacademica'),
        ),
    ]
