# Generated by Django 5.1.7 on 2025-05-22 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_academica', '0001_initial'),
        ('oferta_categoria', '0002_remove_ofertacategoria_fecha_finalizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertacategoria',
            name='id_oferta_academica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oferta_categoria', to='oferta_academica.ofertaacademica'),
        ),
    ]
