# Generated by Django 5.1.7 on 2025-04-23 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('oferta_categoria', '0002_ofertacategoria_precio_univalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertacategoria',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oferta_categoria', to='categoria.categoria'),
        ),
    ]
