# Generated by Django 5.1.7 on 2025-04-25 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_categoria', '0003_alter_ofertacategoria_id_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ofertacategoria',
            options={'verbose_name': 'Oferta Categoria', 'verbose_name_plural': 'Ofertas Categoria'},
        ),
    ]
