# Generated by Django 5.1.7 on 2025-05-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_categoria', '0003_alter_ofertacategoria_id_oferta_academica'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertacategoria',
            name='fecha_finalizacion',
            field=models.DateField(default='2025-04-25'),
            preserve_default=False,
        ),
    ]
