# Generated by Django 5.0.14 on 2025-10-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estado_asistencia',
            field=models.CharField(max_length=20),
        ),
    ]
