# Generated by Django 5.0.14 on 2025-11-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_alter_asistencia_estado_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='sesion',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='comentarios',
            field=models.TextField(blank=True, default='Ninguno', max_length=500),
        ),
    ]
