# Generated by Django 5.0.14 on 2025-11-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_asistencia_sesion_alter_asistencia_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='sesion',
            field=models.CharField(blank=True, null=True),
        ),
    ]
