# Generated by Django 5.1.7 on 2025-04-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCambios',
            fields=[
                ('id_cambio', models.AutoField(primary_key=True, serialize=False)),
                ('id_inscripcion', models.IntegerField()),
                ('tipo_cambio', models.CharField(max_length=50)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo_cambio', models.TextField()),
                ('id_nueva_inscripcion', models.IntegerField()),
                ('id_modulo_nuevo', models.IntegerField()),
                ('id_periodo_aplazado', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Historial de Cambios',
                'verbose_name_plural': 'Historial de Cambios',
                'db_table': 'historial_cambios',
            },
        ),
    ]
