# Generated by Django 5.1.7 on 2025-04-15 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oferta_modulo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grupo', models.CharField(max_length=100)),
                ('id_oferta_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferta_modulo.ofertamodulo')),
            ],
        ),
    ]
