"""
Django settings for semillero_backend project.

Generated by 'django-admin startproject' using Django 5.1.7.

Para más información sobre este archivo, consulta
https://docs.djangoproject.com/en/5.1/topics/settings/

Para la lista completa de configuraciones y sus valores, consulta
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from dotenv import load_dotenv
load_dotenv()
from pathlib import Path
from datetime import timedelta
import os
import dj_database_url
from storages.backends.s3boto3 import S3Boto3Storage

# Construye rutas dentro del proyecto como esta: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Configuración rápida para desarrollo - no apta para producción
# Consulta https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# ADVERTENCIA DE SEGURIDAD: mantén la clave secreta usada en producción en secreto
SECRET_KEY = 'django-insecure-3-!4cm82i1-s5hbg4*m_4x!=wg=lj1$0(-3hb&awt2^0nzpp@o'

# ADVERTENCIA DE SEGURIDAD: no ejecutes con debug activado en producción
DEBUG = True

ALLOWED_HOSTS = [
    '3.148.228.106',
    'localhost',
    '127.0.0.1',
    '0.0.0.0',
    '172.19.0.4',
    '172.18.0.3',
    '190.130.102.234',
    'https://semillero-app.vercel.app',
    'semilleroapp.duckdns.org',
    'ec2-3-148-228-106.us-east-2.compute.amazonaws.com',
    '181.78.17.229'
]

# Definición de aplicaciones

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'django_rest_passwordreset',
    'drf_yasg',
    'psycopg2',
    'estudiante',
    'acudiente',
    'area',
    'asistencia',
    'discapacidad',
    'evaluacion_programa',
    'grupo',
    'historial_cambios',
    'inscripcion',
    'modulo',
    'pago',
    'seguimiento_academico',
    'login',
    'logout',
    'cuenta',
    'administrador',
    'profesor',
    'monitor_academico',
    'monitor_administrativo',
    'oferta_academica',
    'categoria',
    'usuario',
    'oferta_categoria',
    'recuperacion_contrasena',
    'storages',
    "channels",
    "auditlog",
    'prueba_diagnostica',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
         'rest_framework.authentication.TokenAuthentication',
    ),
    'EXCEPTION_HANDLER': 'cuenta.utils.custom_exception_handler',
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ]
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'semillero_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Asegúrate de incluir esta línea
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'semillero_backend.wsgi.application'
ASGI_APPLICATION = 'semillero_backend.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)],  
        },
    },
}
# Base de datos
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
"""
DATABASES = {
    # Configuración para usar SQLite
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'postgres': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'semillero',
        'USER': 'semillero',
        'PASSWORD': 'adminsemillero',
        'HOST': 'database-semillero.cktk40yw6g7t.us-east-1.rds.amazonaws.com',
        'PORT': '5432',
    },
}
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'db_semillero',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'db_semillero',
        'PORT': '5432',
    },
}

# Validación de contraseñas
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]
# Internacionalización
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Archivos estáticos (CSS, JavaScript, Imágenes)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'  # URL base para acceder a los archivos estáticos
STATICFILES_DIRS = [BASE_DIR / 'static']  # Ubicaciones adicionales para buscar archivos
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Donde se recolectan todos los archivos en producción

# Tipo de campo de clave primaria predeterminado
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de CORS
# Define la lista de orígenes permitidos para solicitudes de origen cruzado
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    "https://semillero-app.vercel.app",
    "https://semilleroapp.duckdns.org",
]
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

#Tamaño de datos o archivos
DATA_UPLOAD_MAX_MEMORY_SIZE = 20971520
FILE_UPLOAD_MAX_MEMORY_SIZE = 20971520


# Especifica los métodos HTTP permitidos para solicitudes de origen cruzado
CORS_ALLOW_METHODS = [
    "DELETE",  # Permitir solicitudes DELETE
    "GET",     # Permitir solicitudes GET
    "OPTIONS", # Permitir solicitudes OPTIONS
    "PATCH",   # Permitir solicitudes PATCH
    "POST",    # Permitir solicitudes POST
    "PUT",     # Permitir solicitudes PUT
]

# Especifica los encabezados HTTP permitidos en solicitudes de origen cruzado
CORS_ALLOW_HEADERS = [
    "accept",            # Encabezado Accept
    "accept-encoding",   # Encabezado Accept-Encoding
    "authorization",     # Encabezado Authorization
    "content-type",      # Encabezado Content-Type
    "dnt",               # Encabezado Do Not Track
    "origin",            # Encabezado Origin
    "user-agent",        # Encabezado User-Agent
    "x-csrftoken",       # Encabezado CSRF token
    "x-requested-with",  # Encabezado X-Requested-With
]

AUTH_USER_MODEL = 'cuenta.CustomUser'

#Configuraciones para servidor SMTP google
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = os.getenv('EMAIL_PORT', '587') 
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', '')

# AWS S3 Configuration (condicional)
USE_S3 = os.getenv('USE_S3', 'False') == 'True'

if USE_S3:
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID') # Sin el '' por defecto
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', 'archivos-semillero')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-2')
    AWS_DEFAULT_ACL = None  # Cambiado a None: S3 moderno bloquea ACLs públicas por defecto
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage", # Estándar si no tienes storage_backends.py
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    
    MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/media/'
    print("✅ Usando almacenamiento S3 con Rol de IAM")
else:
    # Configuración para almacenamiento local (Desarrollo)
    FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5 MB en bytes
    
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'
    print("✅ Usando almacenamiento local (desarrollo)")


