# Generated by Django 5.1.7 on 2025-04-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id_acudiente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_acudiente', models.CharField(max_length=100)),
                ('tipo_documento_acudiente', models.CharField(max_length=50)),
                ('numero_documento', models.CharField(max_length=50)),
                ('celular_acudiente', models.CharField(max_length=50)),
                ('direccion_acudiente', models.CharField(max_length=100)),
            ],
        ),
    ]
