# Generated by Django 5.1.7 on 2025-05-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acudiente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acudiente',
            old_name='numero_documento',
            new_name='numero_documento_acudiente',
        ),
        migrations.AddField(
            model_name='acudiente',
            name='apellido_acudiente',
            field=models.CharField(default='Apellido', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acudiente',
            name='direccion_acudiente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acudiente',
            name='tipo_documento_acudiente',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
