# Generated by Django 5.1.7 on 2025-05-07 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acudiente', '0002_rename_numero_documento_acudiente_numero_documento_acudiente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acudiente',
            name='direccion_acudiente',
        ),
    ]
