# Generated by Django 5.0.14 on 2025-10-08 23:29

import django.db.models.deletion
import estudiante.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acudiente', '0001_initial'),
        ('auditlog', '0017_add_actor_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('contrasena', models.CharField(blank=True, max_length=128)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('ciudad_residencia', models.CharField(max_length=100)),
                ('eps', models.CharField(max_length=100)),
                ('grado', models.CharField(max_length=20)),
                ('colegio', models.CharField(default='N/A', max_length=100)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono_fijo', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=15)),
                ('departamento_residencia', models.CharField(max_length=50)),
                ('comuna_residencia', models.CharField(max_length=10)),
                ('direccion_residencia', models.CharField(max_length=255)),
                ('estamento', models.CharField(max_length=50)),
                ('discapacidad', models.BooleanField(default=False)),
                ('tipo_discapacidad', models.CharField(default='Ninguna', max_length=50)),
                ('descripcion_discapacidad', models.TextField(default='Ninguna', max_length=100)),
                ('area_desempeño', models.CharField(blank=True, max_length=100, null=True)),
                ('grado_escolaridad', models.CharField(blank=True, max_length=100, null=True)),
                ('verificacion_foto', models.BooleanField(default=False)),
                ('verificacion_documento_identidad', models.BooleanField(default=False)),
                ('verificacion_informacion', models.BooleanField(default=False)),
                ('estado', models.CharField(default='No revisado', max_length=12)),
                ('documento_identidad', models.FileField(blank=True, help_text='Sube un documento pdf del documento de identidad del estudiante', null=True, upload_to=estudiante.models.documento_identidad_upload_to)),
                ('foto', models.ImageField(blank=True, help_text='Sube una imagen del estudiante', null=True, upload_to=estudiante.models.foto_upload_to)),
                ('acudiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='acudiente.acudiente')),
                ('audit_documento_identidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_documento_identidad', to='auditlog.logentry')),
                ('audit_foto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_foto', to='auditlog.logentry')),
                ('audit_informacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_informacion', to='auditlog.logentry')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['id_estudiante'],
            },
        ),
    ]
