# Generated by Django 5.0.14 on 2026-03-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='estrato',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
