# Generated by Django 5.1.7 on 2025-05-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_estudiante_documento_identidad_estudiante_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='constancia_estudios',
            field=models.FileField(blank=True, help_text='Sube una imagen de la constancia de estudios del estudiante', null=True, upload_to='estudiantes/constancias_estudios/'),
        ),
    ]
