# Generated by Django 5.0.14 on 2025-09-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_estudiante_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='estado',
            field=models.BooleanField(default=None),
        ),
    ]
