# Generated by Django 5.0.14 on 2025-09-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0003_alter_estudiante_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='estado',
            field=models.CharField(default='No revisado', max_length=12),
        ),
    ]
