# Generated by Django 5.0.14 on 2025-09-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0004_alter_estudiante_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='audit_documento_identidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='audit_foto',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='audit_informacion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
