# Generated by Django 5.0.14 on 2025-06-15 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0005_alter_estudiante_constancia_estudios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='ciudad_documento',
        ),
    ]
