# Generated by Django 5.0.14 on 2025-09-29 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0017_add_actor_email'),
        ('estudiante', '0007_alter_estudiante_audit_documento_identidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='audit_documento_identidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_documento_identidad', to='auditlog.logentry'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='audit_foto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_foto', to='auditlog.logentry'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='audit_informacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_informacion', to='auditlog.logentry'),
        ),
    ]
