# Generated by Django 5.0.14 on 2025-09-15 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0007_estudiante_area_desempeño_estudiante_colegio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='constancia_estudios',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='recibo_pago',
        ),
    ]
