# Generated by Django 5.0.14 on 2025-09-15 03:31

import estudiante.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0008_remove_estudiante_constancia_estudios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='documento_identidad',
            field=models.FileField(blank=True, help_text='Sube un documento pdf del documento de identidad del estudiante', null=True, upload_to=estudiante.models.documento_identidad_upload_to),
        ),
    ]
