# Generated by Django 5.1.7 on 2025-05-05 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
        ('categoria', '0001_initial'),
        ('oferta_categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_modulo', models.CharField(max_length=100, unique=True)),
                ('descripcion_modulo', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modulo', to='area.area')),
                ('id_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modulo', to='categoria.categoria')),
                ('id_oferta_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modulo', to='oferta_categoria.ofertacategoria')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
                'ordering': ['id_modulo'],
            },
        ),
    ]
