# Generated by Django 5.0.14 on 2025-09-24 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
        ('categoria', '0001_initial'),
        ('oferta_categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_modulo', models.CharField(max_length=100, unique=True)),
                ('descripcion_modulo', models.TextField(blank=True, null=True)),
                ('intensidad_horaria', models.PositiveIntegerField(default=0)),
                ('dirigido_a', models.CharField(blank=True, max_length=100, null=True)),
                ('incluye', models.TextField(blank=True, null=True)),
                ('imagen_modulo', models.ImageField(blank=True, null=True, upload_to='modulos/')),
                ('estado', models.BooleanField(default=True)),
                ('id_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modulo', to='area.area')),
                ('id_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modulo_categoria', to='categoria.categoria')),
                ('id_oferta_categoria', models.ManyToManyField(blank=True, related_name='modulo', to='oferta_categoria.ofertacategoria')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
                'ordering': ['id_modulo'],
            },
        ),
    ]
