# Generated by Django 5.1.7 on 2025-05-22 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0001_initial'),
        ('oferta_categoria', '0004_ofertacategoria_fecha_finalizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='id_oferta_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modulo', to='oferta_categoria.ofertacategoria'),
        ),
    ]
