# Generated by Django 5.1.7 on 2025-05-22 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('categoria', '0001_initial'),
        ('modulo', '0002_alter_modulo_id_oferta_categoria'),
        ('oferta_categoria', '0004_ofertacategoria_fecha_finalizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='id_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modulo', to='area.area'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='id_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modulo_categoria', to='categoria.categoria'),
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='id_oferta_categoria',
        ),
        migrations.AddField(
            model_name='modulo',
            name='id_oferta_categoria',
            field=models.ManyToManyField(blank=True, related_name='modulos', to='oferta_categoria.ofertacategoria'),
        ),
    ]
