# Generated by Django 5.1.7 on 2025-05-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0003_alter_modulo_id_area_alter_modulo_id_categoria_and_more'),
        ('oferta_categoria', '0005_alter_ofertacategoria_id_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='id_oferta_categoria',
            field=models.ManyToManyField(blank=True, related_name='modulo', to='oferta_categoria.ofertacategoria'),
        ),
    ]
