# Generated by Django 5.1.7 on 2025-06-05 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0005_modulo_ditigido_a_modulo_imagen_modulo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulo',
            old_name='ditigido_a',
            new_name='dirigido_a',
        ),
    ]
