# Generated by Django 5.0.14 on 2025-10-08 23:29

import django.db.models.deletion
import usuario.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('contrasena', models.CharField(blank=True, max_length=128)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('ciudad_residencia', models.CharField(max_length=100)),
                ('eps', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono_fijo', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=15)),
                ('departamento_residencia', models.CharField(max_length=50)),
                ('comuna_residencia', models.CharField(max_length=10)),
                ('direccion_residencia', models.CharField(max_length=255)),
                ('estado', models.CharField(default='No revisado', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='funcionario/foto/')),
                ('documento_identidad_pdf', models.FileField(blank=True, null=True, upload_to=usuario.models.documento_identidad_upload_to)),
                ('rut_pdf', models.FileField(blank=True, null=True, upload_to=usuario.models.rut_upload_to)),
                ('certificado_bancario_pdf', models.FileField(blank=True, null=True, upload_to=usuario.models.certificado_bancario_upload_to)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
