# Generated by Django 5.0.14 on 2025-10-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(default='No revisado', max_length=20),
        ),
    ]
