# Generated by Django 5.0.14 on 2025-10-03 03:55

import usuario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=usuario.models.foto_upload_to),
        ),
    ]
