# Generated by Django 5.1.7 on 2025-04-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id_discapacidad', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_discapacidad', models.CharField(max_length=50, unique=True)),
                ('info_discapacidad', models.TextField()),
            ],
            options={
                'verbose_name': 'Discapacidad',
                'verbose_name_plural': 'Discapacidades',
                'db_table': 'discapacidad',
            },
        ),
    ]
