# Generated by Django 5.1.7 on 2025-05-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discapacidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discapacidad',
            options={'ordering': ['id_discapacidad'], 'verbose_name': 'Discapacidad', 'verbose_name_plural': 'Discapacidades'},
        ),
        migrations.AlterModelTable(
            name='discapacidad',
            table=None,
        ),
    ]
